
// #define BASE_INDEX 60
#define MAIN_RECT_WIDTH 9
#define MAIN_RECT_HEIGHT 6
#define MAIN_RECT_MARGIN 1
#define MIDDLE_CIRCLE_RADIUS 1.5
#define LARG_GOAL_RECT_HEIGHT 5
#define LARG_GOAL_RECT_WIDTH 2
// #define MAIN_RECT_WITDH 9
// #define MAIN_RECT_WITDH 9
// #define MAIN_RECT_WITDH 9